version: '3.3'
services:
  bootserver:
    build: .
    network_mode: host
    privileged: true
    #    networks:
            #      vpcbr:
              #        ipv4_address: 192.16.200.2
        #networks:
        #  vpcbr:
          #    driver: bridge
    #    ipam:
            #     config:
             #       - subnet: 192.16.200.0/24

