version: '3.3'
services:
  bootserver:
    build: .
    network_mode: host
    privileged: true
    environment:
      - DHCPSERVER_ENABLED=true
      - DHCPSERVER_INTERFACE=enp2s0
      - DHCPSERVER_IP=192.16.200.2
      - DHCPSERVER_RANGESTART=192.16.200.3
      - DHCPSERVER_GATEWAY=192.16.200.1
      - DHCPSERVER_DNS=8.8.8.8
